# fly.toml app configuration file generated for estatearmbot--v5-0g on 2025-06-28T18:35:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estatearmbot--v5-0g'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
